# let's go!
language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"

# pyprofit needs gsl
addons:
 apt:
  packages:
   - libgsl0-dev

# Run the build and make sure we can at least import pyprofit correctly
script:
 - python setup.py install
 - python -c "import pyprofit"

# safelist
branches:
 only:
  - master
