# let's go!
language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"

# pyprofit needs gsl
addons:
 apt:
  packages:
   - libgsl0-dev

# Run the build
script: "python setup.py install"

# safelist
branches:
 only:
  - master
